/** @type {import('@commitlint/types').UserConfig} */
export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'header-max-length': [2, 'always', 100],
    'body-max-line-length': [2, 'always', 200],
    'scope-enum': [
      2,
      'always',
      [
        // Sprint scopes (e.g. chore(s0.1): ...)
        's0',
        's0.1',
        's0.2',
        's0.3',
        's0.4',
        's0.5',
        's0.6',
        's0.7',
        's0.8',
        's0.9',
        's0.10',
        's0.11',
        's0.12',
        's0.13',
        's1',
        's2',
        's3',
        's4',
        's5',
        's6',
        's7',
        's8',
        // App scopes
        'web',
        'app',
        'api',
        'docs',
        'email',
        // Package scopes (@eleva/*)
        'ui',
        'auth',
        'db',
        'billing',
        'accounting',
        'scheduling',
        'calendar',
        'notifications',
        'workflows',
        'flags',
        'audit',
        'encryption',
        'ai',
        'crm',
        'compliance',
        'observability',
        'config',
        'eslint-config',
        'typescript-config',
        // Cross-cutting
        'ci',
        'deps',
        'release',
      ],
    ],
  },
};
