export {
  CONSENT_DOCUMENTS,
  CONSENT_DOCUMENT_SLUGS,
  CONSENT_DOCUMENT_VERSION,
  CONSENT_KINDS,
  assertConsentVersionsApprovedForDeployment,
  hashGuestEmail,
  isDraftConsentVersion,
  requiredConsentVersions,
  validateFunnelConsents,
  type ConsentDocument,
  type ConsentKind,
  type FunnelConsentCheck,
  type FunnelConsentGrant,
} from "./consents"
