import {
  UserIcon,
  MapPinIcon,
  ImagesIcon,
  BookOpenIcon,
  TagIcon,
  ShieldIcon,
} from "@eleva/icons"
import { PEXELS } from "@/domains/expert-onboarding/lib/assets"
import { localizedFieldCanProceed } from "@/domains/expert-onboarding/lib/mock-translate"
import type { WizardRegistry, WizardStep } from "@/lib/wizard-types"
import { SESSION_FORMAT_OPTIONS } from "@/lib/wizard-types"

export const POC_A_CHAPTERS = [
  { id: "about", label: "About you", icon: UserIcon },
  { id: "location", label: "Location", icon: MapPinIcon },
  { id: "photos", label: "Photos", icon: ImagesIcon },
  { id: "profile", label: "Public profile", icon: BookOpenIcon },
  { id: "event", label: "First session", icon: BookOpenIcon },
  { id: "pricing", label: "Pricing", icon: TagIcon },
  { id: "publish", label: "Trust & publish", icon: ShieldIcon },
]

export const POC_A_STEPS: WizardStep[] = [
  // Pre-wizard
  {
    id: "p1-specialty",
    title: "What is your area of practice?",
    helper: "Choose the category that best describes your expertise.",
    kind: "specialty-grid",
    illustration: PEXELS.consultation,
    previewKey: "specialty",
    canProceed: (d) => !!d.specialty,
  },
  {
    id: "p2-sub",
    title: "What is your focus within this field?",
    kind: "chip-select",
    canProceed: (d) => !!d.subSpecialty,
  },
  {
    id: "p3-country",
    title: "Where do you primarily practice?",
    helper:
      "Start from the world view — select your country and the map flies in.",
    kind: "country-grid",
    previewKey: "location",
    canProceed: (d) => !!d.practiceCountry,
  },
  {
    id: "p4-city",
    title: "Which city?",
    helper: "The map zooms from your country to the city where you work.",
    kind: "city-search",
    placeholder: "Lisbon, Madrid, São Paulo…",
    previewKey: "location",
    canProceed: (d) => d.city.trim().length >= 2 && d.cityGeocoded,
  },
  {
    id: "p5-intro",
    chapterLabel: "Before we begin",
    title: "Your workspace will be reviewed by our team",
    helper:
      "You'll build your public profile step by step. Compliance and credentials come at the end — nothing goes live until you request it.",
    kind: "interstitial",
    illustration: PEXELS.heroWellness,
    canProceed: () => true,
  },
  {
    id: "p6-name",
    title: "Name your expert workspace",
    helper: "Members see this as your practice name on Eleva.",
    kind: "text",
    placeholder: "Ana Silva Practice",
    canProceed: (d) => d.workspaceName.trim().length >= 3,
  },
  // Chapter 1 — About you
  {
    id: "1-0-about",
    chapterId: "about",
    chapterLabel: "Step 1",
    stepInChapter: 0,
    stepTotalInChapter: 7,
    title: "Tell us about your practice",
    helper:
      "We'll ask about your experience, credentials, and what makes your approach unique.",
    kind: "interstitial",
    showSidebar: true,
    illustration: PEXELS.officeWarm,
    canProceed: () => true,
  },
  {
    id: "1-1-years",
    chapterId: "about",
    chapterLabel: "Step 1",
    stepInChapter: 1,
    stepTotalInChapter: 7,
    title: "How many years have you worked in this field?",
    kind: "stepper",
    showSidebar: true,
    stepperMin: 1,
    stepperMax: 40,
    stepperSuffix: "years",
    canProceed: (d) => d.yearsInField >= 1,
  },
  {
    id: "1-2-cards",
    chapterId: "about",
    chapterLabel: "Step 1",
    stepInChapter: 2,
    stepTotalInChapter: 7,
    title: "Build your expertise profile",
    helper:
      "You'll add title, qualifications, and recognition in the next steps.",
    kind: "credential-cards",
    showSidebar: true,
    canProceed: () => true,
  },
  {
    id: "1-3-title",
    chapterId: "about",
    chapterLabel: "Step 1",
    stepInChapter: 3,
    stepTotalInChapter: 7,
    title: "What is your professional title?",
    kind: "text",
    showSidebar: true,
    maxLength: 60,
    placeholder: "Licensed midwife",
    showAi: true,
    canProceed: (d) => d.professionalTitle.trim().length >= 3,
  },
  {
    id: "1-4-qual",
    chapterId: "about",
    chapterLabel: "Step 1",
    stepInChapter: 4,
    stepTotalInChapter: 7,
    title: "Share your qualifications",
    helper: "Write in any language. Use tabs to review EN, PT, and ES.",
    kind: "localized-field",
    localizedField: "qualifications",
    multiline: true,
    showSidebar: true,
    minLength: 150,
    showAi: true,
    canProceed: (d) => localizedFieldCanProceed(d, "qualifications", 150),
  },
  {
    id: "1-5-recog",
    chapterId: "about",
    chapterLabel: "Step 1",
    stepInChapter: 5,
    stepTotalInChapter: 7,
    title: "Any recognition or publications?",
    helper: "Optional — same write-once, translate-with-AI pattern.",
    kind: "localized-field",
    localizedField: "recognition",
    multiline: true,
    optional: true,
    showSidebar: true,
    canProceed: () => true,
  },
  {
    id: "1-6-linkedin",
    chapterId: "about",
    chapterLabel: "Step 1",
    stepInChapter: 6,
    stepTotalInChapter: 7,
    title: "LinkedIn profile (optional)",
    kind: "text",
    optional: true,
    showSidebar: true,
    placeholder: "https://linkedin.com/in/…",
    canProceed: () => true,
  },
  // Chapter 2 — Location
  {
    id: "2-0-location",
    chapterId: "location",
    chapterLabel: "Step 2",
    stepInChapter: 0,
    stepTotalInChapter: 4,
    title: "Where members meet you",
    helper: "Meeting address and how sessions are delivered.",
    kind: "interstitial",
    showSidebar: true,
    illustration: PEXELS.telehealth,
    canProceed: () => true,
  },
  {
    id: "2-1-address",
    chapterId: "location",
    chapterLabel: "Step 2",
    stepInChapter: 1,
    stepTotalInChapter: 4,
    title: "Search for your meeting address",
    helper:
      "Zoom in to street level — members see where in-person sessions happen.",
    kind: "address-search",
    showSidebar: true,
    previewKey: "location",
    placeholder: "Street, city",
    canProceed: (d) => d.meetingAddress.trim().length >= 5,
  },
  {
    id: "2-2-map",
    chapterId: "location",
    chapterLabel: "Step 2",
    stepInChapter: 2,
    stepTotalInChapter: 4,
    title: "Is the pin in the right place?",
    helper: "Drag the map until the pin sits on your meeting location.",
    kind: "map-confirm",
    showSidebar: true,
    canProceed: () => true,
  },
  {
    id: "2-3-format",
    chapterId: "location",
    chapterLabel: "Step 2",
    stepInChapter: 3,
    stepTotalInChapter: 4,
    title: "How do you deliver sessions?",
    kind: "chip-select",
    chipOptions: SESSION_FORMAT_OPTIONS,
    showSidebar: true,
    canProceed: (d) => !!d.sessionMode,
  },
  // Chapter 3 — Photos
  {
    id: "3-0-photos",
    chapterId: "photos",
    chapterLabel: "Step 3",
    stepInChapter: 0,
    stepTotalInChapter: 3,
    title: "Add photos of you and your space",
    helper:
      "Members connect faster when they see your environment and approach.",
    kind: "interstitial",
    showSidebar: true,
    illustration: PEXELS.yogaCalm,
    canProceed: () => true,
  },
  {
    id: "3-1-upload",
    chapterId: "photos",
    chapterLabel: "Step 3",
    stepInChapter: 1,
    stepTotalInChapter: 3,
    title: "Upload at least 5 photos",
    kind: "upload",
    showSidebar: true,
    previewKey: "photos",
    canProceed: (d) => d.photos.length >= 5,
  },
  {
    id: "3-2-cover",
    chapterId: "photos",
    chapterLabel: "Step 3",
    stepInChapter: 2,
    stepTotalInChapter: 3,
    title: "Choose a cover photo",
    helper: "This is the first image members see.",
    kind: "photo-review",
    showSidebar: true,
    previewKey: "photos",
    canProceed: (d) => d.photos.length >= 5,
  },
  // Chapter 4 — Profile
  {
    id: "4-0-profile",
    chapterId: "profile",
    chapterLabel: "Step 4",
    stepInChapter: 0,
    stepTotalInChapter: 4,
    title: "How members discover you",
    helper:
      "Pick session languages, then write once in your native tongue — EN, PT, and ES on the same screen.",
    kind: "interstitial",
    showSidebar: true,
    canProceed: () => true,
  },
  {
    id: "4-1-langs",
    chapterId: "profile",
    chapterLabel: "Step 4",
    stepInChapter: 1,
    stepTotalInChapter: 4,
    title: "Which languages do you offer sessions in?",
    helper:
      "Select every language members can book with you — all three appear on one screen.",
    kind: "languages",
    showSidebar: true,
    canProceed: (d) => d.languages.length >= 1,
  },
  {
    id: "4-2-headline",
    chapterId: "profile",
    chapterLabel: "Step 4",
    stepInChapter: 2,
    stepTotalInChapter: 4,
    title: "How would you describe yourself?",
    helper:
      "One warm line members see first — write in your language, then translate with AI.",
    kind: "localized-field",
    localizedField: "headline",
    showSidebar: true,
    previewKey: "headline",
    maxLength: 80,
    minLength: 8,
    placeholder: "e.g. Compassionate women's health specialist",
    showAi: true,
    canProceed: (d) => localizedFieldCanProceed(d, "headline", 8),
  },
  {
    id: "4-3-bio",
    chapterId: "profile",
    chapterLabel: "Step 4",
    stepInChapter: 3,
    stepTotalInChapter: 4,
    title: "Your short bio",
    helper:
      "Two or three sentences — all languages visible below after you translate.",
    kind: "localized-field",
    localizedField: "bio",
    multiline: true,
    showSidebar: true,
    previewKey: "bio",
    minLength: 20,
    placeholder: "What makes your approach unique?",
    canProceed: (d) => localizedFieldCanProceed(d, "bio", 20),
  },
  // Chapter 5 — Event
  {
    id: "5-0-event",
    chapterId: "event",
    chapterLabel: "Step 5",
    stepInChapter: 0,
    stepTotalInChapter: 5,
    title: "Your first bookable session",
    helper: "Members need at least one offering to book you.",
    kind: "interstitial",
    showSidebar: true,
    canProceed: () => true,
  },
  {
    id: "5-1-event-title",
    chapterId: "event",
    chapterLabel: "Step 5",
    stepInChapter: 1,
    stepTotalInChapter: 5,
    title: "Name this session",
    helper:
      "Write the title in your language — translate to EN, PT, and ES on one page.",
    kind: "localized-field",
    localizedField: "eventTitle",
    showSidebar: true,
    previewKey: "event",
    placeholder: "Initial consultation — 50 min",
    minLength: 5,
    showAi: true,
    canProceed: (d) => localizedFieldCanProceed(d, "eventTitle", 5),
  },
  {
    id: "5-2-event-desc",
    chapterId: "event",
    chapterLabel: "Step 5",
    stepInChapter: 2,
    stepTotalInChapter: 5,
    title: "Describe this session",
    helper: "Describe the first meeting. Use tabs for each language.",
    kind: "localized-field",
    localizedField: "eventDescription",
    multiline: true,
    showSidebar: true,
    previewKey: "event",
    minLength: 20,
    showAi: true,
    canProceed: (d) => localizedFieldCanProceed(d, "eventDescription", 20),
  },
  {
    id: "5-3-duration",
    chapterId: "event",
    chapterLabel: "Step 5",
    stepInChapter: 3,
    stepTotalInChapter: 5,
    title: "How long is this session?",
    kind: "stepper",
    showSidebar: true,
    stepperMin: 30,
    stepperMax: 120,
    stepperSuffix: "min",
    canProceed: (d) => d.eventDuration >= 30,
  },
  {
    id: "5-4-summary",
    chapterId: "event",
    chapterLabel: "Step 5",
    stepInChapter: 4,
    stepTotalInChapter: 5,
    title: "Review your first offering",
    kind: "event-summary",
    showSidebar: true,
    previewKey: "event",
    canProceed: () => true,
  },
  // Chapter 6 — Pricing
  {
    id: "6-0-pricing",
    chapterId: "pricing",
    chapterLabel: "Step 6",
    stepInChapter: 0,
    stepTotalInChapter: 4,
    title: "Set your pricing",
    helper:
      "You can change this anytime. Eleva shows members what they'll pay.",
    kind: "interstitial",
    showSidebar: true,
    canProceed: () => true,
  },
  {
    id: "6-1-price",
    chapterId: "pricing",
    chapterLabel: "Step 6",
    stepInChapter: 1,
    stepTotalInChapter: 4,
    title: "Price per session",
    kind: "stepper",
    showSidebar: true,
    previewKey: "price",
    stepperMin: 20,
    stepperMax: 300,
    stepperSuffix: "€",
    canProceed: (d) => d.eventPrice >= 20,
  },
  {
    id: "6-2-earnings",
    chapterId: "pricing",
    chapterLabel: "Step 6",
    stepInChapter: 2,
    stepTotalInChapter: 4,
    title: "Your estimated earnings",
    kind: "earnings-info",
    showSidebar: true,
    previewKey: "price",
    canProceed: () => true,
  },
  {
    id: "6-3-offers",
    chapterId: "pricing",
    chapterLabel: "Step 6",
    stepInChapter: 3,
    stepTotalInChapter: 4,
    title: "Offer an introductory discount?",
    helper: "New experts often attract first members with a limited offer.",
    kind: "yesno",
    showSidebar: true,
    canProceed: (d) => d.introOffers !== null,
  },
  // Chapter 7 — Trust
  {
    id: "7-1-telehealth",
    chapterId: "publish",
    chapterLabel: "Step 7",
    stepInChapter: 1,
    stepTotalInChapter: 6,
    title: "Do you follow local telehealth regulations?",
    kind: "yesno",
    showSidebar: true,
    canProceed: (d) => d.telehealthAck !== null,
  },
  {
    id: "7-2-insurance",
    chapterId: "publish",
    chapterLabel: "Step 7",
    stepInChapter: 2,
    stepTotalInChapter: 6,
    title: "Do you carry professional liability insurance?",
    kind: "yesno",
    showSidebar: true,
    canProceed: (d) => d.insuranceAck !== null,
  },
  {
    id: "7-3-tax",
    chapterId: "publish",
    chapterLabel: "Step 7",
    stepInChapter: 3,
    stepTotalInChapter: 6,
    title: "Tax identification",
    helper:
      "Required for experts practicing in your country. Kept private until publish.",
    kind: "tax-id",
    showSidebar: true,
    canProceed: (d) => d.nif.trim().length >= 5,
  },
  {
    id: "7-4-license",
    chapterId: "publish",
    chapterLabel: "Step 7",
    stepInChapter: 4,
    stepTotalInChapter: 6,
    title: "Professional registration",
    kind: "license",
    showSidebar: true,
    canProceed: (d) => d.licenseScope.trim().length >= 3,
  },
  {
    id: "7-5-terms",
    chapterId: "publish",
    chapterLabel: "Step 7",
    stepInChapter: 5,
    stepTotalInChapter: 6,
    title: "Agree to expert terms",
    kind: "terms",
    showSidebar: true,
    canProceed: (d) => d.termsAccepted && d.complianceAck,
  },
  {
    id: "7-6-review",
    chapterId: "publish",
    chapterLabel: "Step 7",
    stepInChapter: 6,
    stepTotalInChapter: 6,
    title: "Review and request to go live",
    helper: "Our team typically reviews within 1–2 business days.",
    kind: "dark-review",
    showSidebar: true,
    previewKey: "full",
    canProceed: () => true,
  },
  {
    id: "post-submit",
    title: "You're all set",
    kind: "post-submit",
    canProceed: () => true,
  },
]

export const POC_A_REGISTRY: WizardRegistry = {
  id: "poc-a",
  chapters: POC_A_CHAPTERS,
  steps: POC_A_STEPS,
}

export function buildPocBSteps(): WizardStep[] {
  const splitIntro: WizardStep = {
    id: "b-split-intro",
    title: "Build your profile with live preview",
    helper: "Every answer updates what members see on the right.",
    kind: "split-intro",
    canProceed: () => true,
  }
  return [
    splitIntro,
    ...POC_A_STEPS.map((step) => ({
      ...step,
      previewKey: step.previewKey ?? inferPreviewKey(step.id),
    })),
  ]
}

function inferPreviewKey(stepId: string): WizardStep["previewKey"] {
  if (stepId.includes("photo") || stepId.startsWith("3-")) return "photos"
  if (stepId.includes("headline") || stepId.startsWith("4-2")) return "headline"
  if (stepId.includes("price") || stepId.startsWith("6-")) return "price"
  if (stepId.startsWith("5-") || stepId.includes("event")) return "event"
  if (stepId.startsWith("p1") || stepId.startsWith("1-3")) return "specialty"
  if (
    stepId.startsWith("2-") ||
    stepId.startsWith("p3") ||
    stepId.startsWith("p4")
  )
    return "location"
  return "full"
}

export const POC_B_REGISTRY: WizardRegistry = {
  id: "poc-b",
  chapters: POC_A_CHAPTERS,
  steps: buildPocBSteps(),
}
